using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[System.Serializable]
public class DailyScoreStorageSaveData
{
	public Dictionary<string, DailyScoreStorageItem> dailyScoreStorageItems = new Dictionary<string, DailyScoreStorageItem>();

    public DailyScoreStorageSaveData(DailyScoreStorageSave dailyScoreStorageSave)
    {
        foreach (KeyValuePair<string, DailyScoreStorageItem> dailyScoreStorageItem in dailyScoreStorageSave.dailyScoreStorageItems)
        {
            dailyScoreStorageItems.Add(dailyScoreStorageItem.Key, dailyScoreStorageItem.Value);
        }
    }
}

[System.Serializable]
public class DailyScoreStorageItem
{
    public string key;
    public string name;
    public long timestamp;
    public float score;
    public DailyScoreStorageType dailyScoreStorageType;
}

public enum DailyScoreStorageType
{
    AutoGeneratedDailyTask,
    Minigame,
}
